name = "Craft to Exile 2 - Feder des Vergessens"
author = "Ravy"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8472d9804cd2924c48d04269e2f043c97f46bd4af5ff2774ba6ae1b3fd9c5f9"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
