name = "Craft to Exile 2 - Feder des Vergessens"
author = "Ravy"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8131025f80482714db008d17209a5fb0a67f007208a841cd054f7e7be379972"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
