name = "Craft to Exile 2 - Feder des Vergessens"
author = "Ravy"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff3cb1f35d6a2c1b2baab505b251a9782659a4ee37373fe87d675f5a1e58a2f9"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
